title: Nikko M. Espiritu
locale: en_PH
owner:
  name: Nikko M. Espiritu
  bio: "This is a sample Jekyll academic website."
  email: nikkomirandaespiritu@gmail.com
  twitter: niikkooespiritu
  linkedin: Nikko Espiritu
  github: espnik
